# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Woke Windows
subtitle: Providing a view into the Boston Police Department
email: nstory@wokewindows.org
description: >- # this means to ignore newlines until "baseurl:"
  Articles, research, and analysis of the Boston Police Department using the Woke Windows database.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.wokewindows.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nathan_story
github_username:  nstory
logo: "/assets/images/brand-128.png"
og_image: "/assets/images/brand-128.png"

# Build settings
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed

# default author; also see _data/authors.yml
author:
  name: "Nathan Story"
  bio: "Founder @ <a href='https://www.wokewindows.org/'>Woke Windows</a>. Computer nerd, FOIA neophyte."
  avatar: "/assets/images/nathan-photo.jpg"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/nathan_story"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nstory"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/nathan_story"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nstory/wokewindows"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
